kind: Deployment
apiVersion: apps/v1
metadata:
  name: metrics-collector-deployment-test
  namespace: open-cluster-management-addon-observability
spec:
  replicas: 1
  selector:
    matchLabels:
      component: metrics-collector-test
  template:
    metadata:
      creationTimestamp: null
      labels:
        component: metrics-collector-test
    spec:
      restartPolicy: Always
      serviceAccountName: endpoint-observability-operator-sa
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      securityContext: {}
      containers:
        - resources:
            requests:
              cpu: 100m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          name: metrics-collector
          command:
            - /usr/bin/metrics-collector
            - '--from=$(FROM)'
            - '--to-upload=$(TO)'
            - >-
              --from-token-file=/var/run/secrets/kubernetes.io/serviceaccount/token
            - '--interval=60s'
            - '--limit-bytes=1073741824'
            - '--label="cluster=CLUSTER_NAME"'
            - '--label="clusterID=CLUSTER_NAME"'
            - '--match={__name__=":node_memory_MemAvailable_bytes:sum"}'
            - '--match={__name__="ALERTS"}'
            - '--match={__name__="authenticated_user_requests"}'
            - '--match={__name__="authentication_attempts"}'
            - '--match={__name__="cluster:capacity_cpu_cores:sum"}'
            - '--match={__name__="cluster:capacity_memory_bytes:sum"}'
            - '--match={__name__="cluster:container_cpu_usage:ratio"}'
            - '--match={__name__="cluster:container_spec_cpu_shares:ratio"}'
            - '--match={__name__="cluster:cpu_usage_cores:sum"}'
            - '--match={__name__="cluster:memory_usage:ratio"}'
            - '--match={__name__="cluster:memory_usage_bytes:sum"}'
            - '--match={__name__="cluster:usage:resources:sum"}'
            - '--match={__name__="cluster_infrastructure_provider"}'
            - '--match={__name__="cluster_version"}'
            - '--match={__name__="cluster_version_payload"}'
            - '--match={__name__="container_cpu_cfs_periods_total"}'
            - '--match={__name__="container_cpu_cfs_throttled_periods_total"}'
            - '--match={__name__="container_spec_cpu_quota"}'
            - '--match={__name__="coredns_dns_request_count_total"}'
            - '--match={__name__="coredns_dns_request_duration_seconds_sum"}'
            - '--match={__name__="coredns_dns_request_type_count_total"}'
            - '--match={__name__="coredns_dns_response_rcode_count_total"}'
            - '--match={__name__="etcd_debugging_mvcc_db_total_size_in_bytes"}'
            - >-
              --match={__name__="etcd_debugging_snap_save_total_duration_seconds_sum"}
            - >-
              --match={__name__="etcd_disk_backend_commit_duration_seconds_bucket"}
            - '--match={__name__="etcd_disk_backend_commit_duration_seconds_sum"}'
            - '--match={__name__="etcd_disk_wal_fsync_duration_seconds_bucket"}'
            - '--match={__name__="etcd_disk_wal_fsync_duration_seconds_sum"}'
            - '--match={__name__="etcd_object_counts"}'
            - '--match={__name__="etcd_network_client_grpc_received_bytes_total"}'
            - '--match={__name__="etcd_network_client_grpc_sent_bytes_total"}'
            - '--match={__name__="etcd_network_peer_received_bytes_total"}'
            - '--match={__name__="etcd_network_peer_sent_bytes_total"}'
            - '--match={__name__="etcd_server_client_requests_total"}'
            - '--match={__name__="etcd_server_has_leader"}'
            - '--match={__name__="etcd_server_health_failures"}'
            - '--match={__name__="etcd_server_leader_changes_seen_total"}'
            - '--match={__name__="etcd_server_proposals_failed_total"}'
            - '--match={__name__="etcd_server_proposals_pending"}'
            - '--match={__name__="etcd_server_proposals_committed_total"}'
            - '--match={__name__="etcd_server_proposals_applied_total"}'
            - '--match={__name__="etcd_server_quota_backend_bytes"}'
            - '--match={__name__="grpc_server_started_total"}'
            - '--match={__name__="haproxy_backend_connection_errors_total"}'
            - '--match={__name__="haproxy_backend_connections_total"}'
            - '--match={__name__="haproxy_backend_current_queue"}'
            - >-
              --match={__name__="haproxy_backend_http_average_response_latency_milliseconds"}
            - '--match={__name__="haproxy_backend_max_sessions"}'
            - '--match={__name__="haproxy_backend_response_errors_total"}'
            - '--match={__name__="haproxy_backend_up"}'
            - '--match={__name__="http_requests_total"}'
            - '--match={__name__="instance:node_filesystem_usage:sum"}'
            - '--match={__name__="instance:node_cpu_utilisation:rate1m"}'
            - '--match={__name__="instance:node_load1_per_cpu:ratio"}'
            - '--match={__name__="instance:node_memory_utilisation:ratio"}'
            - >-
              --match={__name__="instance:node_network_receive_bytes_excluding_lo:rate1m"}
            - >-
              --match={__name__="instance:node_network_receive_drop_excluding_lo:rate1m"}
            - >-
              --match={__name__="instance:node_network_transmit_bytes_excluding_lo:rate1m"}
            - >-
              --match={__name__="instance:node_network_transmit_drop_excluding_lo:rate1m"}
            - '--match={__name__="instance:node_num_cpu:sum"}'
            - '--match={__name__="instance:node_vmstat_pgmajfault:rate1m"}'
            - >-
              --match={__name__="instance_device:node_disk_io_time_seconds:rate1m"}
            - >-
              --match={__name__="instance_device:node_disk_io_time_weighted_seconds:rate1m"}
            - >-
              --match={__name__="kube_daemonset_status_desired_number_scheduled"}
            - '--match={__name__="kube_daemonset_status_number_unavailable"}'
            - '--match={__name__="kube_node_spec_unschedulable"}'
            - '--match={__name__="kube_node_status_allocatable"}'
            - '--match={__name__="kube_node_status_allocatable_cpu_cores"}'
            - '--match={__name__="kube_node_status_allocatable_memory_bytes"}'
            - '--match={__name__="kube_node_status_capacity"}'
            - '--match={__name__="kube_node_status_capacity_pods"}'
            - '--match={__name__="kube_node_status_capacity_cpu_cores"}'
            - '--match={__name__="kube_node_status_condition"}'
            - '--match={__name__="kube_pod_container_resource_limits"}'
            - '--match={__name__="kube_pod_container_resource_limits_cpu_cores"}'
            - >-
              --match={__name__="kube_pod_container_resource_limits_memory_bytes"}
            - '--match={__name__="kube_pod_container_resource_requests"}'
            - >-
              --match={__name__="kube_pod_container_resource_requests_cpu_cores"}
            - >-
              --match={__name__="kube_pod_container_resource_requests_memory_bytes"}
            - '--match={__name__="kube_pod_info"}'
            - '--match={__name__="kube_pod_owner"}'
            - '--match={__name__="kube_resourcequota"}'
            - '--match={__name__="kubelet_running_container_count"}'
            - '--match={__name__="kubelet_runtime_operations"}'
            - >-
              --match={__name__="kubelet_runtime_operations_latency_microseconds"}
            - '--match={__name__="kubelet_volume_stats_available_bytes"}'
            - '--match={__name__="kubelet_volume_stats_capacity_bytes"}'
            - '--match={__name__="kube_persistentvolume_status_phase"}'
            - '--match={__name__="machine_cpu_cores"}'
            - '--match={__name__="machine_memory_bytes"}'
            - '--match={__name__="mixin_pod_workload"}'
            - >-
              --match={__name__="namespace:kube_pod_container_resource_requests_cpu_cores:sum"}
            - >-
              --match={__name__="namespace:kube_pod_container_resource_requests_memory_bytes:sum"}
            - '--match={__name__="namespace:container_memory_usage_bytes:sum"}'
            - >-
              --match={__name__="namespace_cpu:kube_pod_container_resource_requests:sum"}
            - '--match={__name__="namespace_workload_pod:kube_pod_owner:relabel"}'
            - '--match={__name__="node_cpu_seconds_total"}'
            - '--match={__name__="node_filesystem_avail_bytes"}'
            - '--match={__name__="node_filesystem_free_bytes"}'
            - '--match={__name__="node_filesystem_size_bytes"}'
            - '--match={__name__="node_memory_MemAvailable_bytes"}'
            - >-
              --match={__name__="node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate"}
            - '--match={__name__="node_netstat_Tcp_OutSegs"}'
            - '--match={__name__="node_netstat_Tcp_RetransSegs"}'
            - '--match={__name__="node_netstat_TcpExt_TCPSynRetrans"}'
            - '--match={__name__="policyreport_info"}'
            - '--match={__name__="up"}'
            - >-
              --match={__name__="cluster_monitoring_operator_reconcile_errors_total"}
            - >-
              --match={__name__="cluster_monitoring_operator_reconcile_attempts_total"}
            - '--match={__name__="cluster_operator_conditions"}'
            - '--match={__name__="cluster_operator_up"}'
            - '--match={__name__="kube_pod_status_phase"}'
            - >-
              --match={__name__="workqueue_queue_duration_seconds_bucket",job="apiserver"}
            - '--match={__name__="workqueue_adds_total",job="apiserver"}'
            - '--match={__name__="workqueue_depth",job="apiserver"}'
            - '--match={__name__="go_goroutines",job="apiserver"}'
            - '--match={__name__="process_cpu_seconds_total",job="apiserver"}'
            - '--match={__name__="process_resident_memory_bytes",job="apiserver"}'
            - '--match={__name__="container_memory_cache",container!=""}'
            - '--match={__name__="container_memory_rss",container!=""}'
            - '--match={__name__="container_memory_swap",container!=""}'
            - >-
              --match={__name__="container_memory_working_set_bytes",container!=""}
            - >-
              --rename="mixin_pod_workload=namespace_workload_pod:kube_pod_owner:relabel"
            - >-
              --rename="namespace:kube_pod_container_resource_requests_cpu_cores:sum=namespace_cpu:kube_pod_container_resource_requests:sum"
            - >-
              --recordingrule={"name":"apiserver_request_duration_seconds:histogram_quantile_99","query":"histogram_quantile(0.99,sum(rate(apiserver_request_duration_seconds_bucket{job=\"apiserver\",
              verb!=\"WATCH\"}[5m])) by (verb,le))"}
            - >-
              --recordingrule={"name":"apiserver_request_duration_seconds:histogram_quantile_99:instance","query":"histogram_quantile(0.99,
              sum(rate(apiserver_request_duration_seconds_bucket{job=\"apiserver\",
              verb!=\"WATCH\"}[5m])) by (le, instance))"}
            - >-
              --recordingrule={"name":"sum:apiserver_request_total:1h","query":"sum(rate(apiserver_request_total{job=\"apiserver\"}[1h]))
              by(code, instance)"}
            - >-
              --recordingrule={"name":"sum:apiserver_request_total:5m","query":"sum(rate(apiserver_request_total{job=\"apiserver\"}[5m]))
              by(code, instance)"}
            - >-
              --recordingrule={"name":"rpc_rate:grpc_server_handled_total:sum_rate","query":"sum(rate(grpc_server_handled_total{job=\"etcd\",grpc_type=\"unary\",grpc_code!=\"OK\"}[5m]))"}
            - >-
              --recordingrule={"name":"active_streams_watch:grpc_server_handled_total:sum","query":"sum(grpc_server_started_total{job=\"etcd\",grpc_service=\"etcdserverpb.Watch\",grpc_type=\"bidi_stream\"})
              -
              sum(grpc_server_handled_total{job=\"etcd\",grpc_service=\"etcdserverpb.Watch\",grpc_type=\"bidi_stream\"})"}
            - >-
              --recordingrule={"name":"active_streams_lease:grpc_server_handled_total:sum","query":"sum(grpc_server_started_total{job=\"etcd\",grpc_service=\"etcdserverpb.Lease\",grpc_type=\"bidi_stream\"})
              -
              sum(grpc_server_handled_total{job=\"etcd\",grpc_service=\"etcdserverpb.Lease\",grpc_type=\"bidi_stream\"})"}
            - >-
              --recordingrule={"name":"cluster:kube_pod_container_resource_requests:cpu:sum","query":"sum(sum(sum(kube_pod_container_resource_requests{resource=\"cpu\"})
              by (pod,namespace,container) * on(pod,namespace) group_left(phase)
              max(kube_pod_status_phase{phase=~\"Running|Pending|Unknown\"} >0)
              by (pod,namespace,phase)) by (pod,namespace,phase))"}
            - >-
              --recordingrule={"name":"cluster:kube_pod_container_resource_requests:memory:sum","query":"sum(sum(sum(kube_pod_container_resource_requests{resource=\"memory\"})
              by (pod,namespace,container) * on(pod,namespace) group_left(phase)
              max(kube_pod_status_phase{phase=~\"Running|Pending|Unknown\"} >0)
              by (pod,namespace,phase)) by (pod,namespace,phase))"}
          env:
            - name: FROM
              value: 'http://prometheus-k8s.open-cluster-management-addon-observability.svc:9090'
            - name: TO
              value: >-
                https://observatorium-api-open-cluster-management-observability.apps.BASE_DOMAIN/api/metrics/v1/default/api/v1/receive
          imagePullPolicy: Always
          volumeMounts:
            - name: mtlscerts
              mountPath: /tlscerts/certs
            - name: mtlsca
              mountPath: /tlscerts/ca
          terminationMessagePolicy: File
          image: >-
            quay.io/open-cluster-management/metrics-collector@sha256:5f4cb107082e9c1ac12449835e8cb6a442d0fbe75974028d9d66aed5169f47cf
      serviceAccount: endpoint-observability-operator-sa
      volumes:
        - name: mtlscerts
          secret:
            secretName: >-
              observability-controller-open-cluster-management.io-observability-signer-client-cert
            defaultMode: 420
        - name: mtlsca
          secret:
            secretName: observability-managed-cluster-certs
            defaultMode: 420
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
